"""initial schema

Revision ID: b9d74768b13a
Revises: 
Create Date: 2026-08-13 18:52:21.040787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d74768b13a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_normalised', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('operating_areas', sa.JSON(), nullable=True),
    sa.Column('lasrera_number', sa.String(length=30), nullable=True),
    sa.Column('lasrera_verified', sa.Boolean(), nullable=False),
    sa.Column('avg_rating_transparency', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('avg_rating_honesty', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('avg_rating_fee_fairness', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('avg_rating_responsiveness', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('avg_rating_professionalism', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('avg_rating_overall', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('avg_fee_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('profile_claimed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_agents_name_normalised'), 'agents', ['name_normalised'], unique=False)
    op.create_table('commute_destinations',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=30), nullable=False),
    sa.Column('subject_id', sa.String(length=40), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('licence', sa.String(length=60), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_sources_subject', 'data_sources', ['subject_type', 'subject_id'], unique=False)
    op.create_table('lgas',
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('flood_risk', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('centroid_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('centroid_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_last4', sa.String(length=4), nullable=True),
    sa.Column('nin_verified', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=True),
    sa.Column('is_anonymous_default', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('trust_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alerts_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_hash')
    )
    op.create_table('neighbourhoods',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lga_code', sa.String(length=5), nullable=True),
    sa.Column('centroid_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('centroid_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('avg_rent_1bed', sa.Integer(), nullable=True),
    sa.Column('avg_rent_2bed', sa.Integer(), nullable=True),
    sa.Column('avg_rent_3bed', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('avg_power_hours', sa.SmallInteger(), nullable=True),
    sa.Column('avg_security', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('avg_agent_fee_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('commute_vi_min', sa.SmallInteger(), nullable=True),
    sa.Column('flood_risk', sa.String(length=20), nullable=True),
    sa.Column('total_properties', sa.Integer(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('bottleneck_title', sa.String(length=120), nullable=True),
    sa.Column('bottleneck_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lga_code'], ['lgas.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('area_watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.String(length=10), nullable=False),
    sa.Column('notify_reviews', sa.Boolean(), nullable=False),
    sa.Column('notify_floods', sa.Boolean(), nullable=False),
    sa.Column('notify_agent_flags', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['area_code'], ['neighbourhoods.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'area_code', name='uq_watch_user_area')
    )
    op.create_index(op.f('ix_area_watches_area_code'), 'area_watches', ['area_code'], unique=False)
    op.create_index(op.f('ix_area_watches_user_id'), 'area_watches', ['user_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=25), nullable=False),
    sa.Column('geohash_7', sa.String(length=7), nullable=False),
    sa.Column('geohash_8', sa.String(length=8), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('lng', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('location_wkt', sa.Text(), nullable=True),
    sa.Column('address_formal', sa.Text(), nullable=True),
    sa.Column('address_local', sa.Text(), nullable=True),
    sa.Column('address_normalised', sa.Text(), nullable=True),
    sa.Column('w3w_address', sa.String(length=60), nullable=True),
    sa.Column('lga_code', sa.String(length=5), nullable=True),
    sa.Column('neighbourhood_code', sa.String(length=10), nullable=True),
    sa.Column('property_type', sa.String(length=30), nullable=True),
    sa.Column('bedrooms', sa.SmallInteger(), nullable=True),
    sa.Column('flood_zone', sa.String(length=20), nullable=True),
    sa.Column('elevation_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('drainage_dist_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('photo_hash', sa.String(length=64), nullable=True),
    sa.Column('street_view_url', sa.Text(), nullable=True),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_breakdown', sa.JSON(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('verified_reviews', sa.Integer(), nullable=False),
    sa.Column('latest_rent_kobo', sa.Integer(), nullable=True),
    sa.Column('rent_velocity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('area_velocity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rent_percentile', sa.SmallInteger(), nullable=True),
    sa.Column('liquidity_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('traffic_score', sa.String(length=10), nullable=True),
    sa.Column('high_turnover', sa.Boolean(), nullable=False),
    sa.Column('power_hours_avg', sa.SmallInteger(), nullable=True),
    sa.Column('security_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('merged_into', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lga_code'], ['lgas.code'], ),
    sa.ForeignKeyConstraint(['merged_into'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['neighbourhood_code'], ['neighbourhoods.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.create_index(op.f('ix_properties_geohash_7'), 'properties', ['geohash_7'], unique=False)
    op.create_index(op.f('ix_properties_geohash_8'), 'properties', ['geohash_8'], unique=False)
    op.create_index(op.f('ix_properties_lga_code'), 'properties', ['lga_code'], unique=False)
    op.create_index(op.f('ix_properties_neighbourhood_code'), 'properties', ['neighbourhood_code'], unique=False)
    op.create_table('flood_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('when_label', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('evidence', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flood_events_property_id'), 'flood_events', ['property_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('tenancy_start', sa.Date(), nullable=False),
    sa.Column('tenancy_end', sa.Date(), nullable=True),
    sa.Column('still_living', sa.Boolean(), nullable=False),
    sa.Column('rent_amount_kobo', sa.Integer(), nullable=True),
    sa.Column('rent_period', sa.String(length=20), nullable=True),
    sa.Column('agent_fee_kobo', sa.Integer(), nullable=True),
    sa.Column('caution_fee_kobo', sa.Integer(), nullable=True),
    sa.Column('agreement_fee_kobo', sa.Integer(), nullable=True),
    sa.Column('departure_reason', sa.String(length=50), nullable=True),
    sa.Column('rating_landlord', sa.SmallInteger(), nullable=True),
    sa.Column('rating_agent', sa.SmallInteger(), nullable=True),
    sa.Column('rating_property', sa.SmallInteger(), nullable=True),
    sa.Column('rating_water', sa.SmallInteger(), nullable=True),
    sa.Column('rating_power', sa.SmallInteger(), nullable=True),
    sa.Column('rating_security', sa.SmallInteger(), nullable=True),
    sa.Column('rating_noise', sa.SmallInteger(), nullable=True),
    sa.Column('rating_flooding', sa.SmallInteger(), nullable=True),
    sa.Column('rating_neighbourhood', sa.SmallInteger(), nullable=True),
    sa.Column('rating_value', sa.SmallInteger(), nullable=True),
    sa.Column('text_positives', sa.Text(), nullable=True),
    sa.Column('text_warnings', sa.Text(), nullable=True),
    sa.Column('text_negotiation_tips', sa.Text(), nullable=True),
    sa.Column('verification_tier', sa.SmallInteger(), nullable=False),
    sa.Column('verified_tenant', sa.Boolean(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=True),
    sa.Column('owner_response', sa.Text(), nullable=True),
    sa.Column('owner_response_from', sa.String(length=20), nullable=True),
    sa.Column('moderation_status', sa.String(length=20), nullable=False),
    sa.Column('flag_reasons', sa.JSON(), nullable=True),
    sa.Column('flag_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_agent_id'), 'reviews', ['agent_id'], unique=False)
    op.create_index(op.f('ix_reviews_moderation_status'), 'reviews', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_reviews_property_id'), 'reviews', ['property_id'], unique=False)
    op.create_index('ix_reviews_property_status', 'reviews', ['property_id', 'moderation_status'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('saved_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_saved_user_property')
    )
    op.create_index(op.f('ix_saved_properties_property_id'), 'saved_properties', ['property_id'], unique=False)
    op.create_index(op.f('ix_saved_properties_user_id'), 'saved_properties', ['user_id'], unique=False)
    op.create_table('transit_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_options_property_id'), 'transit_options', ['property_id'], unique=False)
    op.create_table('commute_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('destination_code', sa.String(length=10), nullable=False),
    sa.Column('departure_window', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('minutes', sa.SmallInteger(), nullable=False),
    sa.Column('google_estimate_min', sa.SmallInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commute_property_dest', 'commute_reports', ['property_id', 'destination_code'], unique=False)
    op.create_index(op.f('ix_commute_reports_property_id'), 'commute_reports', ['property_id'], unique=False)
    op.create_index(op.f('ix_commute_reports_user_id'), 'commute_reports', ['user_id'], unique=False)
    op.create_table('property_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=48), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('moderation_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_photos_property_status', 'property_photos', ['property_id', 'moderation_status'], unique=False)
    op.create_index(op.f('ix_property_photos_moderation_status'), 'property_photos', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_property_photos_phash'), 'property_photos', ['phash'], unique=False)
    op.create_index(op.f('ix_property_photos_property_id'), 'property_photos', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_photos_review_id'), 'property_photos', ['review_id'], unique=False)
    op.create_index(op.f('ix_property_photos_user_id'), 'property_photos', ['user_id'], unique=False)
    op.create_table('rent_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('period_year', sa.SmallInteger(), nullable=False),
    sa.Column('amount_kobo', sa.Integer(), nullable=False),
    sa.Column('area_avg_kobo', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('agent_fee_kobo', sa.Integer(), nullable=True),
    sa.Column('caution_fee_kobo', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rent_history_property_id'), 'rent_history', ['property_id'], unique=False)
    op.create_index(op.f('ix_rent_history_review_id'), 'rent_history', ['review_id'], unique=False)
    op.create_table('moderation_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('moderator_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['property_photos.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_actions_moderator_id'), 'moderation_actions', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_moderation_actions_photo_id'), 'moderation_actions', ['photo_id'], unique=False)
    op.create_index(op.f('ix_moderation_actions_review_id'), 'moderation_actions', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moderation_actions_review_id'), table_name='moderation_actions')
    op.drop_index(op.f('ix_moderation_actions_photo_id'), table_name='moderation_actions')
    op.drop_index(op.f('ix_moderation_actions_moderator_id'), table_name='moderation_actions')
    op.drop_table('moderation_actions')
    op.drop_index(op.f('ix_rent_history_review_id'), table_name='rent_history')
    op.drop_index(op.f('ix_rent_history_property_id'), table_name='rent_history')
    op.drop_table('rent_history')
    op.drop_index(op.f('ix_property_photos_user_id'), table_name='property_photos')
    op.drop_index(op.f('ix_property_photos_review_id'), table_name='property_photos')
    op.drop_index(op.f('ix_property_photos_property_id'), table_name='property_photos')
    op.drop_index(op.f('ix_property_photos_phash'), table_name='property_photos')
    op.drop_index(op.f('ix_property_photos_moderation_status'), table_name='property_photos')
    op.drop_index('ix_photos_property_status', table_name='property_photos')
    op.drop_table('property_photos')
    op.drop_index(op.f('ix_commute_reports_user_id'), table_name='commute_reports')
    op.drop_index(op.f('ix_commute_reports_property_id'), table_name='commute_reports')
    op.drop_index('ix_commute_property_dest', table_name='commute_reports')
    op.drop_table('commute_reports')
    op.drop_index(op.f('ix_transit_options_property_id'), table_name='transit_options')
    op.drop_table('transit_options')
    op.drop_index(op.f('ix_saved_properties_user_id'), table_name='saved_properties')
    op.drop_index(op.f('ix_saved_properties_property_id'), table_name='saved_properties')
    op.drop_table('saved_properties')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index('ix_reviews_property_status', table_name='reviews')
    op.drop_index(op.f('ix_reviews_property_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_moderation_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_agent_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_flood_events_property_id'), table_name='flood_events')
    op.drop_table('flood_events')
    op.drop_index(op.f('ix_properties_neighbourhood_code'), table_name='properties')
    op.drop_index(op.f('ix_properties_lga_code'), table_name='properties')
    op.drop_index(op.f('ix_properties_geohash_8'), table_name='properties')
    op.drop_index(op.f('ix_properties_geohash_7'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_area_watches_user_id'), table_name='area_watches')
    op.drop_index(op.f('ix_area_watches_area_code'), table_name='area_watches')
    op.drop_table('area_watches')
    op.drop_table('neighbourhoods')
    op.drop_table('users')
    op.drop_table('lgas')
    op.drop_index('ix_data_sources_subject', table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_table('commute_destinations')
    op.drop_index(op.f('ix_agents_name_normalised'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
